In [2]:
#import libraries
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split

In [6]:
#load dataset
data = pd.read_csv("Waveform_dataset.csv")
data .head()

,-0.23,-1.21,1.2,1.23,-0.1,0.12,2.49,1.19,1.34,0.58,...,-0.86,-0.7,0.51,0.34,-0.13,-0.87,0.56,-0.53,0.29,2
0,0.38,0.38,-0.31,-0.09,1.52,1.35,1.49,3.81,2.33,1.34,...,1.28,1.40,0.00,-0.18,0.71,0.04,0.91,-0.79,0.22,0
1,-0.69,1.00,1.08,1.48,2.44,3.39,3.09,4.08,5.48,3.61,...,0.29,1.12,0.60,0.28,2.17,0.18,-0.09,-1.33,1.00,1
2,0.40,0.68,0.27,1.39,1.03,-0.32,-1.23,-0.50,0.11,0.87,...,0.43,-0.30,-0.07,-0.99,-0.75,1.11,1.35,-1.63,0.10,0
3,-0.81,1.59,-0.69,1.16,4.22,4.98,4.52,2.54,5.60,4.66,...,0.62,0.14,1.33,-1.87,1.48,-0.02,-0.58,0.93,0.40,1
4,0.59,0.77,-0.61,1.00,1.80,2.08,2.16,3.59,4.08,3.63,...,1.23,-0.29,-1.62,0.19,-1.04,0.43,-1.82,-1.14,-0.23,1